version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1

  redis:
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379

