version: 2.1

executors:
  default:
    machine: true
    working_directory: ~/workspace

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker


workflows:
  build_and_test:
    jobs:
      - build